// Code generated by tools/Packet.Sdl.CodeGen. DO NOT EDIT.
// Re-exports every SDL page as `extern const` so consumers can
// `#include "ax25sdl.g.h"` and link against the library.

#ifndef AX25SDL_GENERATED_H
#define AX25SDL_GENERATED_H

#include "ax25sdl.h"

extern const StatePage data_link_awaiting_connection;
extern const StatePage data_link_awaiting_release;
extern const StatePage data_link_awaiting_connection22;
extern const StatePage data_link_connected;
extern const StatePage data_link_disconnected;
extern const SubroutinesPage data_link_subroutines;

#endif // AX25SDL_GENERATED_H
