// Code generated by tools/Packet.Sdl.CodeGen from spec-sdl/data-link/awaiting_v22_connection.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project tools/Packet.Sdl.CodeGen` to regenerate.

use crate::types::*;

/// SDL transitions for the AwaitingConnection22 state of the data_link machine.
/// Source: ax.25.2.2.4_Oct_25, figure figc4.6.
pub static DATA_LINK_AWAITING_CONNECTION_22: StatePage = StatePage {
    machine: "data_link",
    state: "AwaitingConnection22",
    source: SdlSource {
        spec: "ax.25.2.2.4_Oct_25",
        figure: "figc4.6",
        url: "https://raw.githubusercontent.com/packethacking/ax25spec/main/doc/media/figc4.6.png",
    },
    transitions: &[
        TransitionSpec {
            id: "t01_dl_connect_request",
            from: "AwaitingConnection22",
            on: "DL_CONNECT_request",
            guard: "",
            actions: &[
                ActionStep { verb: "discard_queue", kind: ActionKind::Processing },
                ActionStep { verb: "set_layer_3_initiated", kind: ActionKind::Processing },
            ],
            next: "AwaitingConnection22",
            notes: "DL-CONNECT while already negotiating v2.2: discard pending queue\nand re-mark layer-3-initiated. Stays in AwaitingConnection22 (the\nexisting T1 / RC counters continue). Mirrors figc4.2's t11.\n",
            references: &[
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "dl_connect_request", line: 1040, note: "case state_1_awaiting_connection / state_5_awaiting_v22_connection share body: discard_i_queue(S); S->layer_3_initiated = 1; '// Keep current state.' Matches figure" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t02_dl_unit_data_request",
            from: "AwaitingConnection22",
            on: "DL_UNIT_DATA_request",
            guard: "",
            actions: &[
                ActionStep { verb: "UI_command", kind: ActionKind::SignalLower },
            ],
            next: "AwaitingConnection22",
            notes: "Connectionless data even while negotiating v2.2 — send UI command,\nstay. Mirrors figc4.2's t12 and figc4.3's t07.\n",
            references: &[
                ImplementationReference { source: "spec_prose", cite: "§6.3.7", quote: "AX.25 uses a special frame for this operation, the Unnumbered Information (UI) frame.", path: "", function: "", line: 0, note: "" },
                ImplementationReference { source: "linux_oot", cite: "", quote: "", path: "net/ax25/ax25_in.c", function: "ax25_rcv", line: 229, note: "UI frames bypass LAPB entirely; outbound UI goes via raw/dgram socket send. State-agnostic, not gated on AX25_STATE_1" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t03_dl_data_request_layer_3_initiated",
            from: "AwaitingConnection22",
            on: "DL_DATA_request",
            guard: "layer_3_initiated",
            actions: &[],
            next: "AwaitingConnection22",
            notes: "verification_pending (carried forward from figc4.2's t13/t14):\nYes/No labels on this diamond are not drawn in the spec PNG —\nTom assumed them when transcribing the graphml. Reading: when L3\ninitiated the connection, the I-frame data is discarded\n(figc4.6 has no \"Push\" action on this branch). Could be inverted —\nflag for upstream check.\n\nDIRECTLY CORROBORATED: direwolf author flags the equivalent figc4.2\ndiamond as confusing (data_request_good_size:1466-1473). direwolf\nreads it as L3-init Yes → discard, !L3-init → push (matches figc4.6\nfigure as drawn).\n",
            references: &[
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "data_request_good_size", line: 1465, note: "case state_1/state_5: 'if (S->layer_3_initiated) { cdata_delete(txdata); break; }'. Erratum at 1467-1473 flags polarity uncertainty but implements per figure" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t04_dl_data_request_not_layer_3_initiated",
            from: "AwaitingConnection22",
            on: "DL_DATA_request",
            guard: "not layer_3_initiated",
            actions: &[
                ActionStep { verb: "push_frame_on_queue", kind: ActionKind::InternalOut },
            ],
            next: "AwaitingConnection22",
            notes: "verification_pending: shares the (label-assumed) diamond with t03.\nReading: peer-initiated connection negotiating v2.2 — queue the\ndata for delivery once Connected.\n",
            references: &[
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "data_request_good_size", line: 1478, note: "Falls through from state_5 case at 1465 into state_3/state_4 push-onto-queue block (1480-1499). Comment 'otherwise fall thru.' Matches figure (!L3-init → push)" },
                ImplementationReference { source: "linux_oot", cite: "", quote: "", path: "net/ax25/af_ax25.c", function: "ax25_sendmsg", line: 1499, note: "Frame appended to sk_write_queue regardless of state; ax25_kick drains only after AX25_STATE_3. No L3-init gating (always 'push')" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t05_i_frame_pops_off_queue_layer_3_initiated",
            from: "AwaitingConnection22",
            on: "I_frame_pops_off_queue",
            guard: "layer_3_initiated",
            actions: &[],
            next: "AwaitingConnection22",
            notes: "verification_pending: shares the (label-assumed) diamond with t03.\n",
            references: &[
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "i_frame_pop_off_queue", line: 6544, note: "case state_1/state_5: 'if (S->layer_3_initiated) { ... cdata_delete(txdata); }' (lines 6560-6570). Erratum at 6555-6558 notes flow chart 'seems backwards' but implements as documented" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t06_i_frame_pops_off_queue_not_layer_3_initiated",
            from: "AwaitingConnection22",
            on: "I_frame_pops_off_queue",
            guard: "not layer_3_initiated",
            actions: &[
                ActionStep { verb: "push_frame_on_queue", kind: ActionKind::InternalOut },
            ],
            next: "AwaitingConnection22",
            notes: "verification_pending: shares the (label-assumed) diamond with t04.\n",
            references: &[
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "i_frame_pop_off_queue", line: 6553, note: "state_5 case, !L3-init branch: comment 'For the case of removing it from the queue and putting it back in we just leave it there.' Functionally equivalent to figure's 'Push Frame Onto Queue' (frame stays on queue)" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t07_all_other_primitives_from_lower_layer",
            from: "AwaitingConnection22",
            on: "all_other_primitives__from_lower_layer",
            guard: "",
            actions: &[],
            next: "AwaitingConnection22",
            notes: "Catch-all for unhandled primitives drawn with d5\n\"Signal reception from Lower Layer\". No action — stay.\n",
            references: &[
                ImplementationReference { source: "linux_oot", cite: "", quote: "", path: "net/ax25/ax25_std_in.c", function: "ax25_std_state1_machine", line: 91, note: "default: break — all unhandled frame types silently ignored in state 1 (Linux fuses spec states 1 and 5)" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t08_control_field_error",
            from: "AwaitingConnection22",
            on: "control_field_error",
            guard: "",
            actions: &[
                ActionStep { verb: "DL_ERROR_indication_L", kind: ActionKind::SignalUpper },
            ],
            next: "AwaitingConnection22",
            notes: "Figure-authoritative DL-ERROR(L) emission. No implementation\nsurfaces this typed error code.\n",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t09_info_not_permitted_in_frame",
            from: "AwaitingConnection22",
            on: "info_not_permitted_in_frame",
            guard: "",
            actions: &[
                ActionStep { verb: "DL_ERROR_indication_M", kind: ActionKind::SignalUpper },
            ],
            next: "AwaitingConnection22",
            notes: "verification_pending: the spec figc4.6 PNG labels this column\n\"Info Field Permitted In Frame\" — the canonical reading per the\nDL-ERROR(M) action (and per figc4.3's equivalent column) is\n\"Info Field NOT Permitted In Frame\". The figc4.6 figure appears\nto have dropped the \"Not\". Encoded with the canonical event id\n`info_not_permitted_in_frame` since the downstream action\n(DL-ERROR(M)) is unambiguous; figure-verbatim label preserved in\nthis note. Candidate upstream-spec typo.\n\nFigure-authoritative DL-ERROR(M) emission. No implementation\nsurfaces this typed error code.\n",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t10_u_or_s_frame_length_error",
            from: "AwaitingConnection22",
            on: "u_or_s_frame_length_error",
            guard: "",
            actions: &[
                ActionStep { verb: "DL_ERROR_indication_N", kind: ActionKind::SignalUpper },
            ],
            next: "AwaitingConnection22",
            notes: "Figure-authoritative DL-ERROR(N) emission. No implementation\nsurfaces this typed error code.\n",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t11_ui_received_p_eq_1",
            from: "AwaitingConnection22",
            on: "UI_received",
            guard: "P_eq_1",
            actions: &[
                ActionStep { verb: "UI_Check", kind: ActionKind::Subroutine },
            ],
            next: "AwaitingConnection22",
            notes: "verification_pending: the spec figc4.6 PNG has the UI-column\n`P == 1?` diamond's Yes/No labels INVERTED compared to figc4.3\n(and §6.3.5 ¶3 prose: \"Any TNC receiving a command frame other\nthan a SABM(E) or UI frame with the P bit set to '1' responds\nwith a DM frame with the F bit set to '1'.\"). The figure here\nshows P==1 Yes → no action (this transition), P==1 No → DM(F=1)\n(t12). Encoded verbatim per Trust-the-Figure (CLAUDE.md §2.1).\nStrong upstream-spec issue candidate — Tom confirmed the swap\nis genuine in the spec PNG.\n\nNo implementation reproduces this branch correctly because\nYes/No is swapped vs the canonical prose reading.\n",
            references: &[
                ImplementationReference { source: "linux_oot", cite: "", quote: "", path: "net/ax25/ax25_in.c", function: "ax25_rcv", line: 229, note: "UI bypass at ax25_in.c:229 ignores P/F entirely; no DM is generated regardless of P — effectively matches the figc4.6 'no action' outcome but for the wrong reason" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t12_ui_received_not_p_eq_1",
            from: "AwaitingConnection22",
            on: "UI_received",
            guard: "not P_eq_1",
            actions: &[
                ActionStep { verb: "UI_Check", kind: ActionKind::Subroutine },
                ActionStep { verb: "DM (F = 1)", kind: ActionKind::SignalLower },
            ],
            next: "AwaitingConnection22",
            notes: "See t11's verification_pending note — figc4.6 has P==1 Yes/No\nswapped vs figc4.3 and §6.3.5 ¶3 prose. This is the figure's\n\"No → DM(F=1)\" branch.\n",
            references: &[],
            loops: &[],
        },
        TransitionSpec {
            id: "t13_dm_received_f_eq_1",
            from: "AwaitingConnection22",
            on: "DM_received",
            guard: "F_eq_1",
            actions: &[
                ActionStep { verb: "discard_I_frame_queue", kind: ActionKind::Processing },
                ActionStep { verb: "DL_DISCONNECT_indication", kind: ActionKind::SignalUpper },
                ActionStep { verb: "stop_T1", kind: ActionKind::Processing },
            ],
            next: "Disconnected",
            notes: "DM(F=1) is a refusal response to our SABME. Discard queue, notify\nupper layer of disconnect, stop T1, drop to Disconnected. Mirrors\nfigc4.2's t02 (which exits to Disconnected on the same condition,\nvia discard_frame_queue rather than discard_i_frame_queue —\nfigure-verbatim wording difference between figc4.2 and figc4.6).\n",
            references: &[
                ImplementationReference { source: "spec_prose", cite: "§6.3.1 ¶4", quote: "When the originating TNC receives a DM response to its SABM(E) frame, it cancels its T1 timer and does not enter the information-transfer state.", path: "", function: "", line: 0, note: "" },
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "dm_frame", line: 4716, note: "case state_5: figure-faithful behaviour is in '#if 0' block (4716-4733) — discard_i_queue, DL-DISCONNECT indication, STOP_T1, enter state_0. The active '#else' block (4734-4765) DIVERGES: on F==1 falls back to v2.0 SABM retry (KPC-3+ workaround). Erratum at 4735: 'copied from FRMR case'" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t14_dm_received_not_f_eq_1",
            from: "AwaitingConnection22",
            on: "DM_received",
            guard: "not F_eq_1",
            actions: &[],
            next: "AwaitingConnection",
            notes: "DM(F=0) drops us back to v2.0 AwaitingConnection (state 1). Read:\npeer doesn't want v2.2 right now — let the v2.0 negotiation cycle\ntake over.\n",
            references: &[
                ImplementationReference { source: "linux_oot", cite: "", quote: "", path: "net/ax25/ax25_std_in.c", function: "ax25_std_state1_machine", line: 81, note: "case AX25_DM with if(pf) gate at line 81 means F=0 falls through with no action; stays in AX25_STATE_1 — matches outcome (Linux fuses states 1 and 5, so 'stay in 1' here is figc4.6's t14 'go to 1')" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t15_ua_received_not_f_eq_1",
            from: "AwaitingConnection22",
            on: "UA_received",
            guard: "not F_eq_1",
            actions: &[
                ActionStep { verb: "DL_ERROR_indication_D", kind: ActionKind::SignalUpper },
            ],
            next: "AwaitingConnection22",
            notes: "UA without F=1 isn't a valid response to our polled SABME — emit\nDL-ERROR(D), keep waiting. Mirrors figc4.2's t04.\n",
            references: &[
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "ua_frame", line: 4917, note: "shared state_1/state_5 case; 'else' branch at 4917 logs 'AX.25 Protocol Error D: UA received without F=1 when SABM or DISC was sent P=1.' and stays in same state. Erratum at 4928: '2006 version is missing yes/no labels on this test.'" },
                ImplementationReference { source: "rax25", cite: "", quote: "", path: "src/state.rs", function: "AwaitingConnection::ua", line: 1207, note: "lines 1207-1209: 'if !f { return vec![Action::DlError(DlError::D)]; }' — matches DL-ERROR(D)" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t16_ua_received_f_eq_1_layer_3_initiated",
            from: "AwaitingConnection22",
            on: "UA_received",
            guard: "F_eq_1 and layer_3_initiated",
            actions: &[
                ActionStep { verb: "DL_CONNECT_confirm", kind: ActionKind::SignalUpper },
                ActionStep { verb: "stop_T1", kind: ActionKind::Processing },
                ActionStep { verb: "start_T3", kind: ActionKind::Processing },
                ActionStep { verb: "V(s) := 0", kind: ActionKind::Processing },
                ActionStep { verb: "V(a) := 0", kind: ActionKind::Processing },
                ActionStep { verb: "V(r) := 0", kind: ActionKind::Processing },
                ActionStep { verb: "Select_T1_Value", kind: ActionKind::Subroutine },
                ActionStep { verb: "MDL_NEGOTIATE_request", kind: ActionKind::InternalOut },
            ],
            next: "Connected",
            notes: "Happy path: UA(F=1) in response to our L3-initiated SABME. Confirm\nto upper layer, run housekeeping, kick MDL-NEGOTIATE Request on\nthe way to Connected. The MDL-NEGOTIATE is what makes this state\nv2.2-specific — figc4.2's t05 doesn't fire it.\n\nOf the 4 implementations, only direwolf fires MDL-NEGOTIATE\n(ua_frame:4910-4912, with erratum that the figure omits it).\n",
            references: &[
                ImplementationReference { source: "spec_prose", cite: "§6.3.1 ¶1", quote: "Reception of the UA response frame by the originating TNC causes it to cancel the T1 timer and set its internal state variables to '0'.", path: "", function: "", line: 0, note: "" },
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "ua_frame", line: 4837, note: "case state_1/state_5 (4834), f==1 + S->layer_3_initiated path: server_link_established at 4846. Common tail 4879-4915: STOP_T1, START_T3, SET_VS/VA/VR(0), select_t1_value, if state_5 then mdl_negotiate_request (4910-4912 with Erratum: figure omits MDL-NEGOTIATE), SET_RC(0), enter state_3" },
                ImplementationReference { source: "rax25", cite: "", quote: "", path: "src/state.rs", function: "AwaitingConnection::ua", line: 1210, note: "'if data.layer3_initiated { debug!(\"DL-CONNECT CONFIRM\"); }' at 1210-1211. Common tail at 1233-1246: stop T1, start T3 (author: '1998 spec says stop T3. 2017 spec says start T3 (page 89), which makes much more sense.'), reset vs/va/vr, rc=0, select_t1_value, → Connected. No MDL-NEGOTIATE (v2.2-only)" },
                ImplementationReference { source: "linux_oot", cite: "", quote: "", path: "net/ax25/ax25_std_in.c", function: "ax25_std_state1_machine", line: 58, note: "case AX25_UA pf set: ax25_calculate_rtt, stop T1, start T3+idle, V(s)/V(r)/V(a):=0, state:=AX25_STATE_3, n2count:=0. No MDL-NEGOTIATE — Linux uses modulus already chosen at SABM/SABME send time. SRT/T1 init via ax25_calculate_rtt rather than spec Select_T1_Value" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t17_ua_received_f_eq_1_not_layer_3_initiated_vs_eq_va",
            from: "AwaitingConnection22",
            on: "UA_received",
            guard: "F_eq_1 and not layer_3_initiated and V_s_eq_V_a",
            actions: &[
                ActionStep { verb: "stop_T1", kind: ActionKind::Processing },
                ActionStep { verb: "start_T3", kind: ActionKind::Processing },
                ActionStep { verb: "V(s) := 0", kind: ActionKind::Processing },
                ActionStep { verb: "V(a) := 0", kind: ActionKind::Processing },
                ActionStep { verb: "V(r) := 0", kind: ActionKind::Processing },
                ActionStep { verb: "Select_T1_Value", kind: ActionKind::Subroutine },
                ActionStep { verb: "MDL_NEGOTIATE_request", kind: ActionKind::InternalOut },
            ],
            next: "Connected",
            notes: "Peer-initiated v2.2 connection coming up with V(s) already aligned.\nNo DL-CONNECT confirm (upper layer wasn't expecting one). Mirrors\nfigc4.2's t06 with the added MDL-NEGOTIATE Request.\n",
            references: &[
                ImplementationReference { source: "rax25", cite: "", quote: "", path: "src/state.rs", function: "AwaitingConnection::ua", line: 1212, note: "implicit else: !layer3_initiated && vs==va falls through if/else if at 1210-1232, hits common tail at 1233-1246 (stop T1, start T3, reset counters, select_t1_value, → Connected). No MDL-NEGOTIATE" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t18_ua_received_f_eq_1_not_layer_3_initiated_vs_neq_va",
            from: "AwaitingConnection22",
            on: "UA_received",
            guard: "F_eq_1 and not layer_3_initiated and not V_s_eq_V_a",
            actions: &[
                ActionStep { verb: "SRT := Initial Default", kind: ActionKind::Processing },
                ActionStep { verb: "T1V := 2 * SRT", kind: ActionKind::Processing },
                ActionStep { verb: "start_T3", kind: ActionKind::Processing },
                ActionStep { verb: "DL_CONNECT_confirm", kind: ActionKind::SignalUpper },
                ActionStep { verb: "stop_T1", kind: ActionKind::Processing },
                ActionStep { verb: "start_T3", kind: ActionKind::Processing },
                ActionStep { verb: "V(s) := 0", kind: ActionKind::Processing },
                ActionStep { verb: "V(a) := 0", kind: ActionKind::Processing },
                ActionStep { verb: "V(r) := 0", kind: ActionKind::Processing },
                ActionStep { verb: "Select_T1_Value", kind: ActionKind::Subroutine },
                ActionStep { verb: "MDL_NEGOTIATE_request", kind: ActionKind::InternalOut },
            ],
            next: "Connected",
            notes: "V(s) ≠ V(a) recovery branch: re-init timer values + Start T3\nBEFORE the standard housekeeping which ALSO restarts T3. Same\n\"Start T3 twice\" pattern as figc4.2's t07. rax25 author flagged\nthis exact pattern as a spec bug at src/state.rs:1226 (\"bug in\nthe 2017 spec...start T1, then immediately stop it again\").\n",
            references: &[
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "ua_frame", line: 4848, note: "case state_1/state_5, f==1, !L3, 'else if (S->vs != S->va)' branch (4848-4877). Active '#if 1' block (Erratum: '2006 version has this') does INIT_T1V_SRT then START_T3 (with note that it's pointless) and server_link_established. Then common tail at 4879-4915 (housekeeping + MDL-NEGOTIATE for state_5)" },
                ImplementationReference { source: "rax25", cite: "", quote: "", path: "src/state.rs", function: "AwaitingConnection::ua", line: 1212, note: "'!data.layer3_initiated && vs!=va' branch (1212-1232): srt=srt_default, t1v=srt+srt, common tail. Author comments: 'We're awaiting a connection confirmation, but vs!=va? What does that mean?' and 'bug in the 2017 spec. This path says to start T1, then immediately stop it again.' warn!('Strange state entered: UA received while vs != va')" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t19_t1_expiry_rc_eq_n2",
            from: "AwaitingConnection22",
            on: "T1_expiry",
            guard: "RC_eq_N2",
            actions: &[
                ActionStep { verb: "discard_frame_queue", kind: ActionKind::Processing },
                ActionStep { verb: "DL_ERROR_indication_G", kind: ActionKind::SignalUpper },
                ActionStep { verb: "DL_DISCONNECT_indication", kind: ActionKind::SignalUpper },
            ],
            next: "Disconnected",
            notes: "Retry exhaustion while awaiting UA for our SABME — discard queue,\nemit DL-ERROR(G), DL-DISCONNECT indication, drop to Disconnected.\nMirrors figc4.2's t08 with the additional Discard Frame Queue\nstep (figure-authoritative).\n",
            references: &[
                ImplementationReference { source: "spec_prose", cite: "§6.3.1 ¶2", quote: "The originating TNC tries to establish a connection until it has tried unsuccessfully N2 times.", path: "", function: "", line: 0, note: "" },
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "t1_expiry", line: 5461, note: "case state_1/state_5 (5450-5451). 'if (S->rc == S->n2_retry)' branch (5461-5468): discard_i_queue, server_link_terminated, enter state_0. DL-ERROR(G) implied via 'Failed to connect after %d tries' but not emitted as a typed error" },
                ImplementationReference { source: "rax25", cite: "", quote: "", path: "src/state.rs", function: "AwaitingConnection::t1", line: 1189, note: "lines 1189-1195: 'if data.rc == data.n2 { data.clear_iframe_queue(); vec![Action::DlError(DlError::G), Action::State(Box::new(Disconnected::new()))] }'. Author comment 1192: 'Typo in 1998 spec: G, not g.' No explicit DL-DISCONNECT indication" },
                ImplementationReference { source: "linux_oot", cite: "", quote: "", path: "net/ax25/ax25_std_timer.c", function: "ax25_std_t1timer_expiry", line: 124, note: "if (n2count == n2): for AX25_MODULUS calls ax25_disconnect(ETIMEDOUT). For AX25_EMODULUS instead drops to v2.0 (modulus:=AX25_MODULUS, n2count:=0, resend SABM) — Linux's v2.2→v2.0 fallback rather than spec disconnect" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t20_t1_expiry_rc_neq_n2",
            from: "AwaitingConnection22",
            on: "T1_expiry",
            guard: "not RC_eq_N2",
            actions: &[
                ActionStep { verb: "RC := RC + 1", kind: ActionKind::Processing },
                ActionStep { verb: "SABME (P = 1)", kind: ActionKind::SignalLower },
                ActionStep { verb: "Select_T1_Value", kind: ActionKind::Subroutine },
                ActionStep { verb: "start_T1", kind: ActionKind::Processing },
            ],
            next: "AwaitingConnection22",
            notes: "Below retry limit — bump RC, resend SABME(P=1), recalc T1V via\nSelect T1 Value, restart T1, keep waiting. Mirrors figc4.2's t09\n(which retransmits SABM instead of SABME).\n",
            references: &[
                ImplementationReference { source: "spec_prose", cite: "§6.3.1 ¶2", quote: "If the distant TNC doesn't respond before T1 times out, the originating TNC resends the SABM frame and starts T1 running again.", path: "", function: "", line: 0, note: "" },
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "t1_expiry", line: 5469, note: "case state_1/state_5, 'else' branch (5469-5484): SET_RC(rc+1), build SABME (state_5) or SABM (state_1) via 'frame_type_U_SABME : frame_type_U_SABM' ternary at 5479, lm_data_request, select_t1_value, START_T1. Matches figure" },
                ImplementationReference { source: "rax25", cite: "", quote: "", path: "src/state.rs", function: "AwaitingConnection::t1", line: 1196, note: "1196-1201: else branch increments rc, select_t1_value, t1.start(srt), sends SendSabm{pf:true}. NB: rax25 sends SABM not SABME — no v2.2-aware state" },
                ImplementationReference { source: "linux_oot", cite: "", quote: "", path: "net/ax25/ax25_std_timer.c", function: "ax25_std_t1timer_expiry", line: 134, note: "else branch: n2count++, retransmit SABM or SABME based on current modulus. No Select_T1_Value — T1 implicitly restarted by ax25_send_control machinery" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t21_frmr_received",
            from: "AwaitingConnection22",
            on: "FRMR_received",
            guard: "",
            actions: &[
                ActionStep { verb: "SRT := Initial Default", kind: ActionKind::Processing },
                ActionStep { verb: "T1V := 2 * SRT", kind: ActionKind::Processing },
                ActionStep { verb: "Establish_Data_Link", kind: ActionKind::Subroutine },
                ActionStep { verb: "set_layer_3_initiated", kind: ActionKind::Processing },
                ActionStep { verb: "set_version_2_0", kind: ActionKind::Processing },
            ],
            next: "AwaitingConnection",
            notes: "FRMR while negotiating v2.2 — peer is v2.0 (or pre-2.2 in v2.0\nmode), so re-initialise timers, run the Establish Data Link\nsubroutine, force v2.0, and fall to AwaitingConnection (state 1).\n\nOnly direwolf implements this — with its own erratum at 5047\nflagging spec inconsistency: \"State 1 clears it. State 5 sets it.\nWhy not the same?\" re: layer_3_initiated.\n",
            references: &[
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "frmr_frame", line: 5035, note: "case state_5 (5035-5051): INIT_T1V_SRT, set_version_2_0 (Erratum at 5044: 'Need to force v2.0. This is not in flow chart'), establish_data_link, S->layer_3_initiated = 1 (Erratum at 5047: 'State 1 clears it. State 5 sets it. Why not the same?'), enter state_1" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t22_sabme_received",
            from: "AwaitingConnection22",
            on: "SABME_received",
            guard: "",
            actions: &[
                ActionStep { verb: "F := P", kind: ActionKind::Processing },
                ActionStep { verb: "UA", kind: ActionKind::SignalLower },
            ],
            next: "AwaitingConnection22",
            notes: "SABME from peer while our own SABME is in flight — collision\nrecovery: respond UA, stay (our own SABME may still get its UA).\nMirrors figc4.2's t23 SABM-while-SABM-pending collision.\n",
            references: &[
                ImplementationReference { source: "spec_prose", cite: "§6.3.6.2", quote: "If sent and received SABM(E) or DISC command frames are the same, both TNCs send a UA response at the earliest opportunity, and both devices enter the indicated state.", path: "", function: "", line: 0, note: "" },
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "sabm_e_frame", line: 4406, note: "case state_5, 'if (extended)' branch (4406-4413): build UA response with f=p, lm_data_request, '// stay in state 5'. Matches figure" },
                ImplementationReference { source: "linux_oot", cite: "", quote: "", path: "net/ax25/ax25_std_in.c", function: "ax25_std_state1_machine", line: 48, note: "case AX25_SABME: modulus:=AX25_EMODULUS, window:=EWINDOW, send UA(F=pf). Stays in AX25_STATE_1 — same fused state for v2.0/v2.2" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t23_sabm_received",
            from: "AwaitingConnection22",
            on: "SABM_received",
            guard: "",
            actions: &[
                ActionStep { verb: "F := P", kind: ActionKind::Processing },
                ActionStep { verb: "UA", kind: ActionKind::SignalLower },
                ActionStep { verb: "set_version_2_0", kind: ActionKind::Processing },
            ],
            next: "AwaitingConnection",
            notes: "SABM (v2.0) from peer while we're trying v2.2 — peer doesn't\nsupport v2.2 or is downgrading. Reply UA, set version 2.0, fall to\nv2.0 AwaitingConnection (state 1).\n",
            references: &[
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "sabm_e_frame", line: 4415, note: "case state_5, 'else' branch — SABM (not extended) at 4415-4423: build UA response with f=p, lm_data_request, enter state_1. DIVERGES: direwolf does NOT explicitly call set_version_2_0 here as figure prescribes" },
                ImplementationReference { source: "rax25", cite: "", quote: "", path: "src/state.rs", function: "AwaitingConnection::sabm", line: 1250, note: "1250-1252: returns SendUa{pf:packet.poll}. Matches UA(F:=P) but omits 'Set Version 2.0' and there's no v2.2 state to leave" },
                ImplementationReference { source: "linux_oot", cite: "", quote: "", path: "net/ax25/ax25_std_in.c", function: "ax25_std_state1_machine", line: 42, note: "case AX25_SABM: modulus:=AX25_MODULUS, window:=WINDOW, send UA(F=pf). Stays AX25_STATE_1 (no v2.0/v2.2 state distinction)" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t24_disc_received",
            from: "AwaitingConnection22",
            on: "DISC_received",
            guard: "",
            actions: &[
                ActionStep { verb: "F := P", kind: ActionKind::Processing },
                ActionStep { verb: "DM", kind: ActionKind::SignalLower },
            ],
            next: "AwaitingConnection22",
            notes: "DISC from peer while negotiating v2.2: respond DM (we're not\nconnected yet), stay in AwaitingConnection22 waiting for our\nSABME's UA. Unlike figc4.3 (Awaiting Release), which responds UA\nto a cross-DISC, figc4.6 responds DM because we haven't\nestablished the link yet.\n",
            references: &[
                ImplementationReference { source: "direwolf", cite: "", quote: "", path: "src/ax25_link.c", function: "disc_frame", line: 4531, note: "case state_0/state_1/state_5 shared body (4529-4542): build DM response with f=p, lm_data_request, '// keep current state, 0, 1, or 5.' Matches figure" },
                ImplementationReference { source: "linux_oot", cite: "", quote: "", path: "net/ax25/ax25_std_in.c", function: "ax25_std_state1_machine", line: 54, note: "case AX25_DISC: ax25_send_control(AX25_DM, pf, RESPONSE) — F:=P via pf, stays in state 1" },
            ],
            loops: &[],
        },
        TransitionSpec {
            id: "t25_all_other_primitives_from_upper_layer",
            from: "AwaitingConnection22",
            on: "all_other_primitives__from_upper_layer",
            guard: "",
            actions: &[],
            next: "AwaitingConnection22",
            notes: "Catch-all for unhandled primitives drawn with d5\n\"Signal reception from upper layer\". No action — stay.\n",
            references: &[],
            loops: &[],
        },
    ],
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn source_figure() {
        assert_eq!(DATA_LINK_AWAITING_CONNECTION_22.source.figure, "figc4.6");
    }

    #[test]
    fn transitions_are_present() {
        assert_eq!(DATA_LINK_AWAITING_CONNECTION_22.transitions.len(), 25);
    }

    #[test]
    fn t01_dl_connect_request() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t01_dl_connect_request")
            .expect("transition t01_dl_connect_request not found");
        assert_eq!(tx.on, "DL_CONNECT_request");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.actions.len(), 2);
        assert_eq!(tx.actions[0].verb, "discard_queue");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "set_layer_3_initiated");
        assert_eq!(tx.actions[1].kind, ActionKind::Processing);
    }

    #[test]
    fn t02_dl_unit_data_request() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t02_dl_unit_data_request")
            .expect("transition t02_dl_unit_data_request not found");
        assert_eq!(tx.on, "DL_UNIT_DATA_request");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "UI_command");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalLower);
    }

    #[test]
    fn t03_dl_data_request_layer_3_initiated() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t03_dl_data_request_layer_3_initiated")
            .expect("transition t03_dl_data_request_layer_3_initiated not found");
        assert_eq!(tx.on, "DL_DATA_request");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.guard, "layer_3_initiated");
        assert_eq!(tx.actions.len(), 0);
    }

    #[test]
    fn t04_dl_data_request_not_layer_3_initiated() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t04_dl_data_request_not_layer_3_initiated")
            .expect("transition t04_dl_data_request_not_layer_3_initiated not found");
        assert_eq!(tx.on, "DL_DATA_request");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.guard, "not layer_3_initiated");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "push_frame_on_queue");
        assert_eq!(tx.actions[0].kind, ActionKind::InternalOut);
    }

    #[test]
    fn t05_i_frame_pops_off_queue_layer_3_initiated() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t05_i_frame_pops_off_queue_layer_3_initiated")
            .expect("transition t05_i_frame_pops_off_queue_layer_3_initiated not found");
        assert_eq!(tx.on, "I_frame_pops_off_queue");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.guard, "layer_3_initiated");
        assert_eq!(tx.actions.len(), 0);
    }

    #[test]
    fn t06_i_frame_pops_off_queue_not_layer_3_initiated() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t06_i_frame_pops_off_queue_not_layer_3_initiated")
            .expect("transition t06_i_frame_pops_off_queue_not_layer_3_initiated not found");
        assert_eq!(tx.on, "I_frame_pops_off_queue");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.guard, "not layer_3_initiated");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "push_frame_on_queue");
        assert_eq!(tx.actions[0].kind, ActionKind::InternalOut);
    }

    #[test]
    fn t07_all_other_primitives_from_lower_layer() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t07_all_other_primitives_from_lower_layer")
            .expect("transition t07_all_other_primitives_from_lower_layer not found");
        assert_eq!(tx.on, "all_other_primitives__from_lower_layer");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.actions.len(), 0);
    }

    #[test]
    fn t08_control_field_error() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t08_control_field_error")
            .expect("transition t08_control_field_error not found");
        assert_eq!(tx.on, "control_field_error");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "DL_ERROR_indication_L");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalUpper);
    }

    #[test]
    fn t09_info_not_permitted_in_frame() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t09_info_not_permitted_in_frame")
            .expect("transition t09_info_not_permitted_in_frame not found");
        assert_eq!(tx.on, "info_not_permitted_in_frame");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "DL_ERROR_indication_M");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalUpper);
    }

    #[test]
    fn t10_u_or_s_frame_length_error() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t10_u_or_s_frame_length_error")
            .expect("transition t10_u_or_s_frame_length_error not found");
        assert_eq!(tx.on, "u_or_s_frame_length_error");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "DL_ERROR_indication_N");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalUpper);
    }

    #[test]
    fn t11_ui_received_p_eq_1() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t11_ui_received_p_eq_1")
            .expect("transition t11_ui_received_p_eq_1 not found");
        assert_eq!(tx.on, "UI_received");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.guard, "P_eq_1");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "UI_Check");
        assert_eq!(tx.actions[0].kind, ActionKind::Subroutine);
    }

    #[test]
    fn t12_ui_received_not_p_eq_1() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t12_ui_received_not_p_eq_1")
            .expect("transition t12_ui_received_not_p_eq_1 not found");
        assert_eq!(tx.on, "UI_received");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.guard, "not P_eq_1");
        assert_eq!(tx.actions.len(), 2);
        assert_eq!(tx.actions[0].verb, "UI_Check");
        assert_eq!(tx.actions[0].kind, ActionKind::Subroutine);
        assert_eq!(tx.actions[1].verb, "DM (F = 1)");
        assert_eq!(tx.actions[1].kind, ActionKind::SignalLower);
    }

    #[test]
    fn t13_dm_received_f_eq_1() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t13_dm_received_f_eq_1")
            .expect("transition t13_dm_received_f_eq_1 not found");
        assert_eq!(tx.on, "DM_received");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.guard, "F_eq_1");
        assert_eq!(tx.actions.len(), 3);
        assert_eq!(tx.actions[0].verb, "discard_I_frame_queue");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "DL_DISCONNECT_indication");
        assert_eq!(tx.actions[1].kind, ActionKind::SignalUpper);
        assert_eq!(tx.actions[2].verb, "stop_T1");
        assert_eq!(tx.actions[2].kind, ActionKind::Processing);
    }

    #[test]
    fn t14_dm_received_not_f_eq_1() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t14_dm_received_not_f_eq_1")
            .expect("transition t14_dm_received_not_f_eq_1 not found");
        assert_eq!(tx.on, "DM_received");
        assert_eq!(tx.next, "AwaitingConnection");
        assert_eq!(tx.guard, "not F_eq_1");
        assert_eq!(tx.actions.len(), 0);
    }

    #[test]
    fn t15_ua_received_not_f_eq_1() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t15_ua_received_not_f_eq_1")
            .expect("transition t15_ua_received_not_f_eq_1 not found");
        assert_eq!(tx.on, "UA_received");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.guard, "not F_eq_1");
        assert_eq!(tx.actions.len(), 1);
        assert_eq!(tx.actions[0].verb, "DL_ERROR_indication_D");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalUpper);
    }

    #[test]
    fn t16_ua_received_f_eq_1_layer_3_initiated() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t16_ua_received_f_eq_1_layer_3_initiated")
            .expect("transition t16_ua_received_f_eq_1_layer_3_initiated not found");
        assert_eq!(tx.on, "UA_received");
        assert_eq!(tx.next, "Connected");
        assert_eq!(tx.guard, "F_eq_1 and layer_3_initiated");
        assert_eq!(tx.actions.len(), 8);
        assert_eq!(tx.actions[0].verb, "DL_CONNECT_confirm");
        assert_eq!(tx.actions[0].kind, ActionKind::SignalUpper);
        assert_eq!(tx.actions[1].verb, "stop_T1");
        assert_eq!(tx.actions[1].kind, ActionKind::Processing);
        assert_eq!(tx.actions[2].verb, "start_T3");
        assert_eq!(tx.actions[2].kind, ActionKind::Processing);
        assert_eq!(tx.actions[3].verb, "V(s) := 0");
        assert_eq!(tx.actions[3].kind, ActionKind::Processing);
        assert_eq!(tx.actions[4].verb, "V(a) := 0");
        assert_eq!(tx.actions[4].kind, ActionKind::Processing);
        assert_eq!(tx.actions[5].verb, "V(r) := 0");
        assert_eq!(tx.actions[5].kind, ActionKind::Processing);
        assert_eq!(tx.actions[6].verb, "Select_T1_Value");
        assert_eq!(tx.actions[6].kind, ActionKind::Subroutine);
        assert_eq!(tx.actions[7].verb, "MDL_NEGOTIATE_request");
        assert_eq!(tx.actions[7].kind, ActionKind::InternalOut);
    }

    #[test]
    fn t17_ua_received_f_eq_1_not_layer_3_initiated_vs_eq_va() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t17_ua_received_f_eq_1_not_layer_3_initiated_vs_eq_va")
            .expect("transition t17_ua_received_f_eq_1_not_layer_3_initiated_vs_eq_va not found");
        assert_eq!(tx.on, "UA_received");
        assert_eq!(tx.next, "Connected");
        assert_eq!(tx.guard, "F_eq_1 and not layer_3_initiated and V_s_eq_V_a");
        assert_eq!(tx.actions.len(), 7);
        assert_eq!(tx.actions[0].verb, "stop_T1");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "start_T3");
        assert_eq!(tx.actions[1].kind, ActionKind::Processing);
        assert_eq!(tx.actions[2].verb, "V(s) := 0");
        assert_eq!(tx.actions[2].kind, ActionKind::Processing);
        assert_eq!(tx.actions[3].verb, "V(a) := 0");
        assert_eq!(tx.actions[3].kind, ActionKind::Processing);
        assert_eq!(tx.actions[4].verb, "V(r) := 0");
        assert_eq!(tx.actions[4].kind, ActionKind::Processing);
        assert_eq!(tx.actions[5].verb, "Select_T1_Value");
        assert_eq!(tx.actions[5].kind, ActionKind::Subroutine);
        assert_eq!(tx.actions[6].verb, "MDL_NEGOTIATE_request");
        assert_eq!(tx.actions[6].kind, ActionKind::InternalOut);
    }

    #[test]
    fn t18_ua_received_f_eq_1_not_layer_3_initiated_vs_neq_va() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t18_ua_received_f_eq_1_not_layer_3_initiated_vs_neq_va")
            .expect("transition t18_ua_received_f_eq_1_not_layer_3_initiated_vs_neq_va not found");
        assert_eq!(tx.on, "UA_received");
        assert_eq!(tx.next, "Connected");
        assert_eq!(
            tx.guard,
            "F_eq_1 and not layer_3_initiated and not V_s_eq_V_a"
        );
        assert_eq!(tx.actions.len(), 11);
        assert_eq!(tx.actions[0].verb, "SRT := Initial Default");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "T1V := 2 * SRT");
        assert_eq!(tx.actions[1].kind, ActionKind::Processing);
        assert_eq!(tx.actions[2].verb, "start_T3");
        assert_eq!(tx.actions[2].kind, ActionKind::Processing);
        assert_eq!(tx.actions[3].verb, "DL_CONNECT_confirm");
        assert_eq!(tx.actions[3].kind, ActionKind::SignalUpper);
        assert_eq!(tx.actions[4].verb, "stop_T1");
        assert_eq!(tx.actions[4].kind, ActionKind::Processing);
        assert_eq!(tx.actions[5].verb, "start_T3");
        assert_eq!(tx.actions[5].kind, ActionKind::Processing);
        assert_eq!(tx.actions[6].verb, "V(s) := 0");
        assert_eq!(tx.actions[6].kind, ActionKind::Processing);
        assert_eq!(tx.actions[7].verb, "V(a) := 0");
        assert_eq!(tx.actions[7].kind, ActionKind::Processing);
        assert_eq!(tx.actions[8].verb, "V(r) := 0");
        assert_eq!(tx.actions[8].kind, ActionKind::Processing);
        assert_eq!(tx.actions[9].verb, "Select_T1_Value");
        assert_eq!(tx.actions[9].kind, ActionKind::Subroutine);
        assert_eq!(tx.actions[10].verb, "MDL_NEGOTIATE_request");
        assert_eq!(tx.actions[10].kind, ActionKind::InternalOut);
    }

    #[test]
    fn t19_t1_expiry_rc_eq_n2() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t19_t1_expiry_rc_eq_n2")
            .expect("transition t19_t1_expiry_rc_eq_n2 not found");
        assert_eq!(tx.on, "T1_expiry");
        assert_eq!(tx.next, "Disconnected");
        assert_eq!(tx.guard, "RC_eq_N2");
        assert_eq!(tx.actions.len(), 3);
        assert_eq!(tx.actions[0].verb, "discard_frame_queue");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "DL_ERROR_indication_G");
        assert_eq!(tx.actions[1].kind, ActionKind::SignalUpper);
        assert_eq!(tx.actions[2].verb, "DL_DISCONNECT_indication");
        assert_eq!(tx.actions[2].kind, ActionKind::SignalUpper);
    }

    #[test]
    fn t20_t1_expiry_rc_neq_n2() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t20_t1_expiry_rc_neq_n2")
            .expect("transition t20_t1_expiry_rc_neq_n2 not found");
        assert_eq!(tx.on, "T1_expiry");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.guard, "not RC_eq_N2");
        assert_eq!(tx.actions.len(), 4);
        assert_eq!(tx.actions[0].verb, "RC := RC + 1");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "SABME (P = 1)");
        assert_eq!(tx.actions[1].kind, ActionKind::SignalLower);
        assert_eq!(tx.actions[2].verb, "Select_T1_Value");
        assert_eq!(tx.actions[2].kind, ActionKind::Subroutine);
        assert_eq!(tx.actions[3].verb, "start_T1");
        assert_eq!(tx.actions[3].kind, ActionKind::Processing);
    }

    #[test]
    fn t21_frmr_received() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t21_frmr_received")
            .expect("transition t21_frmr_received not found");
        assert_eq!(tx.on, "FRMR_received");
        assert_eq!(tx.next, "AwaitingConnection");
        assert_eq!(tx.actions.len(), 5);
        assert_eq!(tx.actions[0].verb, "SRT := Initial Default");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "T1V := 2 * SRT");
        assert_eq!(tx.actions[1].kind, ActionKind::Processing);
        assert_eq!(tx.actions[2].verb, "Establish_Data_Link");
        assert_eq!(tx.actions[2].kind, ActionKind::Subroutine);
        assert_eq!(tx.actions[3].verb, "set_layer_3_initiated");
        assert_eq!(tx.actions[3].kind, ActionKind::Processing);
        assert_eq!(tx.actions[4].verb, "set_version_2_0");
        assert_eq!(tx.actions[4].kind, ActionKind::Processing);
    }

    #[test]
    fn t22_sabme_received() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t22_sabme_received")
            .expect("transition t22_sabme_received not found");
        assert_eq!(tx.on, "SABME_received");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.actions.len(), 2);
        assert_eq!(tx.actions[0].verb, "F := P");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "UA");
        assert_eq!(tx.actions[1].kind, ActionKind::SignalLower);
    }

    #[test]
    fn t23_sabm_received() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t23_sabm_received")
            .expect("transition t23_sabm_received not found");
        assert_eq!(tx.on, "SABM_received");
        assert_eq!(tx.next, "AwaitingConnection");
        assert_eq!(tx.actions.len(), 3);
        assert_eq!(tx.actions[0].verb, "F := P");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "UA");
        assert_eq!(tx.actions[1].kind, ActionKind::SignalLower);
        assert_eq!(tx.actions[2].verb, "set_version_2_0");
        assert_eq!(tx.actions[2].kind, ActionKind::Processing);
    }

    #[test]
    fn t24_disc_received() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t24_disc_received")
            .expect("transition t24_disc_received not found");
        assert_eq!(tx.on, "DISC_received");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.actions.len(), 2);
        assert_eq!(tx.actions[0].verb, "F := P");
        assert_eq!(tx.actions[0].kind, ActionKind::Processing);
        assert_eq!(tx.actions[1].verb, "DM");
        assert_eq!(tx.actions[1].kind, ActionKind::SignalLower);
    }

    #[test]
    fn t25_all_other_primitives_from_upper_layer() {
        let tx = DATA_LINK_AWAITING_CONNECTION_22
            .transitions
            .iter()
            .find(|x| x.id == "t25_all_other_primitives_from_upper_layer")
            .expect("transition t25_all_other_primitives_from_upper_layer not found");
        assert_eq!(tx.on, "all_other_primitives__from_upper_layer");
        assert_eq!(tx.next, "AwaitingConnection22");
        assert_eq!(tx.actions.len(), 0);
    }
}
