// Code generated by tools/Packet.Sdl.CodeGen. DO NOT EDIT.
// Re-exports every SDL page so consumers can `use ax25sdl::DATA_LINK_DISCONNECTED`.

pub mod types;
pub use types::*;

#[path = "awaiting_connection.g.rs"]
pub mod awaiting_connection;
#[path = "awaiting_release.g.rs"]
pub mod awaiting_release;
#[path = "awaiting_v22_connection.g.rs"]
pub mod awaiting_v22_connection;
#[path = "connected.g.rs"]
pub mod connected;
#[path = "disconnected.g.rs"]
pub mod disconnected;
#[path = "subroutines.g.rs"]
pub mod subroutines;

pub use awaiting_connection::*;
pub use awaiting_release::*;
pub use awaiting_v22_connection::*;
pub use connected::*;
pub use disconnected::*;
pub use subroutines::*;
