# Code generated by tools/Packet.Sdl.CodeGen. DO NOT EDIT.
# Re-exports every SDL page so consumers can `from ax25sdl import DATA_LINK_CONNECTED`.

import importlib.util as _importlib_util
from pathlib import Path as _Path

from .types import (
    ActionKind,
    ActionStep,
    ImplementationReference,
    LoopRange,
    SdlSource,
    StatePage,
    SubroutinePath,
    SubroutineSpec,
    SubroutinesPage,
    TransitionSpec,
)


def _load(stem: str, attr: str) -> object:
    path = _Path(__file__).parent / f"{stem}.g.py"
    spec = _importlib_util.spec_from_file_location(f"ax25sdl._gen_{stem}", path)
    assert spec is not None and spec.loader is not None
    module = _importlib_util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return getattr(module, attr)


DATA_LINK_AWAITING_CONNECTION = _load("awaiting_connection", "DATA_LINK_AWAITING_CONNECTION")
DATA_LINK_AWAITING_RELEASE = _load("awaiting_release", "DATA_LINK_AWAITING_RELEASE")
DATA_LINK_AWAITING_CONNECTION_22 = _load("awaiting_v22_connection", "DATA_LINK_AWAITING_CONNECTION_22")
DATA_LINK_CONNECTED = _load("connected", "DATA_LINK_CONNECTED")
DATA_LINK_DISCONNECTED = _load("disconnected", "DATA_LINK_DISCONNECTED")
DATA_LINK_SUBROUTINES = _load("subroutines", "DATA_LINK_SUBROUTINES")

__all__ = [
    "ActionKind",
    "ActionStep",
    "ImplementationReference",
    "LoopRange",
    "SdlSource",
    "StatePage",
    "SubroutinePath",
    "SubroutineSpec",
    "SubroutinesPage",
    "TransitionSpec",
    "DATA_LINK_AWAITING_CONNECTION",
    "DATA_LINK_AWAITING_RELEASE",
    "DATA_LINK_AWAITING_CONNECTION_22",
    "DATA_LINK_CONNECTED",
    "DATA_LINK_DISCONNECTED",
    "DATA_LINK_SUBROUTINES",
]
