# Code generated by tools/Packet.Sdl.CodeGen from spec-sdl/data-link/disconnected.sdl.yaml.
# DO NOT EDIT. Run `dotnet run --project tools/Packet.Sdl.CodeGen` to regenerate.

from . import DATA_LINK_DISCONNECTED
from .types import ActionKind


def test_source_figure() -> None:
    assert DATA_LINK_DISCONNECTED.source.figure == "figc4.1"


def test_transitions_are_present() -> None:
    assert len(DATA_LINK_DISCONNECTED.transitions) == 17


def test_t01_dl_disconnect_request() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t01_dl_disconnect_request"),
        None,
    )
    assert t is not None, "transition t01_dl_disconnect_request not found"
    assert t.on == "DL_DISCONNECT_request"
    assert t.next == "Disconnected"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "DL_DISCONNECT_confirm"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER


def test_t02_dl_unit_data_request() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t02_dl_unit_data_request"),
        None,
    )
    assert t is not None, "transition t02_dl_unit_data_request not found"
    assert t.on == "DL_UNIT_DATA_request"
    assert t.next == "Disconnected"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "UI_command"
    assert t.actions[0].kind == ActionKind.SIGNAL_LOWER


def test_t03_dl_connect_request() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t03_dl_connect_request"),
        None,
    )
    assert t is not None, "transition t03_dl_connect_request not found"
    assert t.on == "DL_CONNECT_request"
    assert t.next == "AwaitingConnection"
    assert len(t.actions) == 4
    assert t.actions[0].verb == "SRT := Initial Default"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "T1V := 2 * SRT"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Establish_Data_Link"
    assert t.actions[2].kind == ActionKind.SUBROUTINE
    assert t.actions[3].verb == "set_layer_3_initiated"
    assert t.actions[3].kind == ActionKind.PROCESSING


def test_t04_all_other_primitives_from_lower_layer() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t04_all_other_primitives_from_lower_layer"),
        None,
    )
    assert t is not None, "transition t04_all_other_primitives_from_lower_layer not found"
    assert t.on == "all_other_primitives__from_lower_layer"
    assert t.next == "Disconnected"
    assert len(t.actions) == 0


def test_t05_all_other_commands() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t05_all_other_commands"),
        None,
    )
    assert t is not None, "transition t05_all_other_commands not found"
    assert t.on == "all_other_commands"
    assert t.next == "Disconnected"
    assert len(t.actions) == 2
    assert t.actions[0].verb == "F := P"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "DM"
    assert t.actions[1].kind == ActionKind.SIGNAL_LOWER


def test_t06_all_other_primitives_from_upper_layer() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t06_all_other_primitives_from_upper_layer"),
        None,
    )
    assert t is not None, "transition t06_all_other_primitives_from_upper_layer not found"
    assert t.on == "all_other_primitives__from_upper_layer"
    assert t.next == "Disconnected"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "discard_primitive"
    assert t.actions[0].kind == ActionKind.PROCESSING


def test_t07_control_field_error() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t07_control_field_error"),
        None,
    )
    assert t is not None, "transition t07_control_field_error not found"
    assert t.on == "control_field_error"
    assert t.next == "Disconnected"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "DL_ERROR_indication_L"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER


def test_t08_info_not_permitted_in_frame() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t08_info_not_permitted_in_frame"),
        None,
    )
    assert t is not None, "transition t08_info_not_permitted_in_frame not found"
    assert t.on == "info_not_permitted_in_frame"
    assert t.next == "Disconnected"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "DL_ERROR_indication_M"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER


def test_t09_u_or_s_frame_length_error() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t09_u_or_s_frame_length_error"),
        None,
    )
    assert t is not None, "transition t09_u_or_s_frame_length_error not found"
    assert t.on == "u_or_s_frame_length_error"
    assert t.next == "Disconnected"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "DL_ERROR_indication_N"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER


def test_t10_ua_received() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t10_ua_received"),
        None,
    )
    assert t is not None, "transition t10_ua_received not found"
    assert t.on == "UA_received"
    assert t.next == "Disconnected"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "DL_ERROR_indication_C_D"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER


def test_t11_ui_received_p_eq_1() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t11_ui_received_p_eq_1"),
        None,
    )
    assert t is not None, "transition t11_ui_received_p_eq_1 not found"
    assert t.on == "UI_received"
    assert t.next == "Disconnected"
    assert t.guard == "P_eq_1"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "UI_Check"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "F := 1"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "DM"
    assert t.actions[2].kind == ActionKind.SIGNAL_LOWER


def test_t12_ui_received_p_eq_0() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t12_ui_received_p_eq_0"),
        None,
    )
    assert t is not None, "transition t12_ui_received_p_eq_0 not found"
    assert t.on == "UI_received"
    assert t.next == "Disconnected"
    assert t.guard == "not P_eq_1"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "UI_Check"
    assert t.actions[0].kind == ActionKind.SUBROUTINE


def test_t13_disc_received() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t13_disc_received"),
        None,
    )
    assert t is not None, "transition t13_disc_received not found"
    assert t.on == "DISC_received"
    assert t.next == "Disconnected"
    assert len(t.actions) == 2
    assert t.actions[0].verb == "F := P"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "DM"
    assert t.actions[1].kind == ActionKind.SIGNAL_LOWER


def test_t14_sabm_received_able() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t14_sabm_received_able"),
        None,
    )
    assert t is not None, "transition t14_sabm_received_able not found"
    assert t.on == "SABM_received"
    assert t.next == "Connected"
    assert t.guard == "able_to_establish"
    assert len(t.actions) == 12
    assert t.actions[0].verb == "F := P"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "set_version_2_0"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "UA"
    assert t.actions[2].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[3].verb == "Clear_Exception_Conditions"
    assert t.actions[3].kind == ActionKind.SUBROUTINE
    assert t.actions[4].verb == "V(s) := 0"
    assert t.actions[4].kind == ActionKind.PROCESSING
    assert t.actions[5].verb == "V(a) := 0"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "V(r) := 0"
    assert t.actions[6].kind == ActionKind.PROCESSING
    assert t.actions[7].verb == "DL_CONNECT_indication"
    assert t.actions[7].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[8].verb == "SRT := Initial Default"
    assert t.actions[8].kind == ActionKind.PROCESSING
    assert t.actions[9].verb == "T1V := 2 * SRT"
    assert t.actions[9].kind == ActionKind.PROCESSING
    assert t.actions[10].verb == "start_T3"
    assert t.actions[10].kind == ActionKind.PROCESSING
    assert t.actions[11].verb == "RC := 0"
    assert t.actions[11].kind == ActionKind.PROCESSING


def test_t15_sabm_received_unable() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t15_sabm_received_unable"),
        None,
    )
    assert t is not None, "transition t15_sabm_received_unable not found"
    assert t.on == "SABM_received"
    assert t.next == "Disconnected"
    assert t.guard == "not able_to_establish"
    assert len(t.actions) == 2
    assert t.actions[0].verb == "F := P"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "DM"
    assert t.actions[1].kind == ActionKind.SIGNAL_LOWER


def test_t16_sabme_received_able() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t16_sabme_received_able"),
        None,
    )
    assert t is not None, "transition t16_sabme_received_able not found"
    assert t.on == "SABME_received"
    assert t.next == "Connected"
    assert t.guard == "able_to_establish"
    assert len(t.actions) == 12
    assert t.actions[0].verb == "F := P"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "set_version_2_2"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "UA"
    assert t.actions[2].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[3].verb == "Clear_Exception_Conditions"
    assert t.actions[3].kind == ActionKind.SUBROUTINE
    assert t.actions[4].verb == "V(s) := 0"
    assert t.actions[4].kind == ActionKind.PROCESSING
    assert t.actions[5].verb == "V(a) := 0"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "V(r) := 0"
    assert t.actions[6].kind == ActionKind.PROCESSING
    assert t.actions[7].verb == "DL_CONNECT_indication"
    assert t.actions[7].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[8].verb == "SRT := Initial Default"
    assert t.actions[8].kind == ActionKind.PROCESSING
    assert t.actions[9].verb == "T1V := 2 * SRT"
    assert t.actions[9].kind == ActionKind.PROCESSING
    assert t.actions[10].verb == "start_T3"
    assert t.actions[10].kind == ActionKind.PROCESSING
    assert t.actions[11].verb == "RC := 0"
    assert t.actions[11].kind == ActionKind.PROCESSING


def test_t17_sabme_received_unable() -> None:
    t = next(
        (x for x in DATA_LINK_DISCONNECTED.transitions if x.id == "t17_sabme_received_unable"),
        None,
    )
    assert t is not None, "transition t17_sabme_received_unable not found"
    assert t.on == "SABME_received"
    assert t.next == "Disconnected"
    assert t.guard == "not able_to_establish"
    assert len(t.actions) == 2
    assert t.actions[0].verb == "F := P"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "DM"
    assert t.actions[1].kind == ActionKind.SIGNAL_LOWER

