// Code generated by tools/Packet.Sdl.CodeGen from spec-sdl/data-link/disconnected.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project tools/Packet.Sdl.CodeGen` to regenerate.

package ax25sdl

import "testing"

func TestDataLinkDisconnected_SourceFigure(t *testing.T) {
	if got := DataLinkDisconnected.Source.Figure; got != "figc4.1" {
		t.Errorf("Source.Figure = %q, want figc4.1", got)
	}
}

func TestDataLinkDisconnected_TransitionsArePresent(t *testing.T) {
	if got := len(DataLinkDisconnected.Transitions); got != 17 {
		t.Errorf("len(Transitions) = %d, want 17", got)
	}
}

func TestDataLinkDisconnected_t01_dl_disconnect_request(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t01_dl_disconnect_request" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t01_dl_disconnect_request not found")
	}
	if tx.On != "DL_DISCONNECT_request" {
		t.Errorf("On = %q, want DL_DISCONNECT_request", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL_DISCONNECT_confirm" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL_DISCONNECT_confirm")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkDisconnected_t02_dl_unit_data_request(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t02_dl_unit_data_request" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t02_dl_unit_data_request not found")
	}
	if tx.On != "DL_UNIT_DATA_request" {
		t.Errorf("On = %q, want DL_UNIT_DATA_request", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "UI_command" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "UI_command")
	}
	if tx.Actions[0].Kind != SignalLower {
		t.Errorf("Actions[0].Kind = %v, want SignalLower", tx.Actions[0].Kind)
	}
}

func TestDataLinkDisconnected_t03_dl_connect_request(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t03_dl_connect_request" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t03_dl_connect_request not found")
	}
	if tx.On != "DL_CONNECT_request" {
		t.Errorf("On = %q, want DL_CONNECT_request", tx.On)
	}
	if tx.Next != "AwaitingConnection" {
		t.Errorf("Next = %q, want AwaitingConnection", tx.Next)
	}
	if got := len(tx.Actions); got != 4 {
		t.Fatalf("len(Actions) = %d, want 4", got)
	}
	if tx.Actions[0].Verb != "SRT := Initial Default" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "SRT := Initial Default")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "T1V := 2 * SRT" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "T1V := 2 * SRT")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "Establish_Data_Link" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "Establish_Data_Link")
	}
	if tx.Actions[2].Kind != Subroutine {
		t.Errorf("Actions[2].Kind = %v, want Subroutine", tx.Actions[2].Kind)
	}
	if tx.Actions[3].Verb != "set_layer_3_initiated" {
		t.Errorf("Actions[3].Verb = %q, want %q", tx.Actions[3].Verb, "set_layer_3_initiated")
	}
	if tx.Actions[3].Kind != Processing {
		t.Errorf("Actions[3].Kind = %v, want Processing", tx.Actions[3].Kind)
	}
}

func TestDataLinkDisconnected_t04_all_other_primitives_from_lower_layer(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t04_all_other_primitives_from_lower_layer" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t04_all_other_primitives_from_lower_layer not found")
	}
	if tx.On != "all_other_primitives__from_lower_layer" {
		t.Errorf("On = %q, want all_other_primitives__from_lower_layer", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if got := len(tx.Actions); got != 0 {
		t.Fatalf("len(Actions) = %d, want 0", got)
	}
}

func TestDataLinkDisconnected_t05_all_other_commands(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t05_all_other_commands" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t05_all_other_commands not found")
	}
	if tx.On != "all_other_commands" {
		t.Errorf("On = %q, want all_other_commands", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "DM" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "DM")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
}

func TestDataLinkDisconnected_t06_all_other_primitives_from_upper_layer(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t06_all_other_primitives_from_upper_layer" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t06_all_other_primitives_from_upper_layer not found")
	}
	if tx.On != "all_other_primitives__from_upper_layer" {
		t.Errorf("On = %q, want all_other_primitives__from_upper_layer", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "discard_primitive" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "discard_primitive")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
}

func TestDataLinkDisconnected_t07_control_field_error(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t07_control_field_error" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t07_control_field_error not found")
	}
	if tx.On != "control_field_error" {
		t.Errorf("On = %q, want control_field_error", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL_ERROR_indication_L" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL_ERROR_indication_L")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkDisconnected_t08_info_not_permitted_in_frame(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t08_info_not_permitted_in_frame" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t08_info_not_permitted_in_frame not found")
	}
	if tx.On != "info_not_permitted_in_frame" {
		t.Errorf("On = %q, want info_not_permitted_in_frame", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL_ERROR_indication_M" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL_ERROR_indication_M")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkDisconnected_t09_u_or_s_frame_length_error(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t09_u_or_s_frame_length_error" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t09_u_or_s_frame_length_error not found")
	}
	if tx.On != "u_or_s_frame_length_error" {
		t.Errorf("On = %q, want u_or_s_frame_length_error", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL_ERROR_indication_N" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL_ERROR_indication_N")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkDisconnected_t10_ua_received(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t10_ua_received" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t10_ua_received not found")
	}
	if tx.On != "UA_received" {
		t.Errorf("On = %q, want UA_received", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "DL_ERROR_indication_C_D" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "DL_ERROR_indication_C_D")
	}
	if tx.Actions[0].Kind != SignalUpper {
		t.Errorf("Actions[0].Kind = %v, want SignalUpper", tx.Actions[0].Kind)
	}
}

func TestDataLinkDisconnected_t11_ui_received_p_eq_1(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t11_ui_received_p_eq_1" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t11_ui_received_p_eq_1 not found")
	}
	if tx.On != "UI_received" {
		t.Errorf("On = %q, want UI_received", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if tx.Guard != "P_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "P_eq_1")
	}
	if got := len(tx.Actions); got != 3 {
		t.Fatalf("len(Actions) = %d, want 3", got)
	}
	if tx.Actions[0].Verb != "UI_Check" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "UI_Check")
	}
	if tx.Actions[0].Kind != Subroutine {
		t.Errorf("Actions[0].Kind = %v, want Subroutine", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "F := 1" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "F := 1")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "DM" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "DM")
	}
	if tx.Actions[2].Kind != SignalLower {
		t.Errorf("Actions[2].Kind = %v, want SignalLower", tx.Actions[2].Kind)
	}
}

func TestDataLinkDisconnected_t12_ui_received_p_eq_0(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t12_ui_received_p_eq_0" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t12_ui_received_p_eq_0 not found")
	}
	if tx.On != "UI_received" {
		t.Errorf("On = %q, want UI_received", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if tx.Guard != "not P_eq_1" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not P_eq_1")
	}
	if got := len(tx.Actions); got != 1 {
		t.Fatalf("len(Actions) = %d, want 1", got)
	}
	if tx.Actions[0].Verb != "UI_Check" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "UI_Check")
	}
	if tx.Actions[0].Kind != Subroutine {
		t.Errorf("Actions[0].Kind = %v, want Subroutine", tx.Actions[0].Kind)
	}
}

func TestDataLinkDisconnected_t13_disc_received(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t13_disc_received" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t13_disc_received not found")
	}
	if tx.On != "DISC_received" {
		t.Errorf("On = %q, want DISC_received", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "DM" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "DM")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
}

func TestDataLinkDisconnected_t14_sabm_received_able(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t14_sabm_received_able" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t14_sabm_received_able not found")
	}
	if tx.On != "SABM_received" {
		t.Errorf("On = %q, want SABM_received", tx.On)
	}
	if tx.Next != "Connected" {
		t.Errorf("Next = %q, want Connected", tx.Next)
	}
	if tx.Guard != "able_to_establish" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "able_to_establish")
	}
	if got := len(tx.Actions); got != 12 {
		t.Fatalf("len(Actions) = %d, want 12", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "set_version_2_0" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "set_version_2_0")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "UA" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "UA")
	}
	if tx.Actions[2].Kind != SignalLower {
		t.Errorf("Actions[2].Kind = %v, want SignalLower", tx.Actions[2].Kind)
	}
	if tx.Actions[3].Verb != "Clear_Exception_Conditions" {
		t.Errorf("Actions[3].Verb = %q, want %q", tx.Actions[3].Verb, "Clear_Exception_Conditions")
	}
	if tx.Actions[3].Kind != Subroutine {
		t.Errorf("Actions[3].Kind = %v, want Subroutine", tx.Actions[3].Kind)
	}
	if tx.Actions[4].Verb != "V(s) := 0" {
		t.Errorf("Actions[4].Verb = %q, want %q", tx.Actions[4].Verb, "V(s) := 0")
	}
	if tx.Actions[4].Kind != Processing {
		t.Errorf("Actions[4].Kind = %v, want Processing", tx.Actions[4].Kind)
	}
	if tx.Actions[5].Verb != "V(a) := 0" {
		t.Errorf("Actions[5].Verb = %q, want %q", tx.Actions[5].Verb, "V(a) := 0")
	}
	if tx.Actions[5].Kind != Processing {
		t.Errorf("Actions[5].Kind = %v, want Processing", tx.Actions[5].Kind)
	}
	if tx.Actions[6].Verb != "V(r) := 0" {
		t.Errorf("Actions[6].Verb = %q, want %q", tx.Actions[6].Verb, "V(r) := 0")
	}
	if tx.Actions[6].Kind != Processing {
		t.Errorf("Actions[6].Kind = %v, want Processing", tx.Actions[6].Kind)
	}
	if tx.Actions[7].Verb != "DL_CONNECT_indication" {
		t.Errorf("Actions[7].Verb = %q, want %q", tx.Actions[7].Verb, "DL_CONNECT_indication")
	}
	if tx.Actions[7].Kind != SignalUpper {
		t.Errorf("Actions[7].Kind = %v, want SignalUpper", tx.Actions[7].Kind)
	}
	if tx.Actions[8].Verb != "SRT := Initial Default" {
		t.Errorf("Actions[8].Verb = %q, want %q", tx.Actions[8].Verb, "SRT := Initial Default")
	}
	if tx.Actions[8].Kind != Processing {
		t.Errorf("Actions[8].Kind = %v, want Processing", tx.Actions[8].Kind)
	}
	if tx.Actions[9].Verb != "T1V := 2 * SRT" {
		t.Errorf("Actions[9].Verb = %q, want %q", tx.Actions[9].Verb, "T1V := 2 * SRT")
	}
	if tx.Actions[9].Kind != Processing {
		t.Errorf("Actions[9].Kind = %v, want Processing", tx.Actions[9].Kind)
	}
	if tx.Actions[10].Verb != "start_T3" {
		t.Errorf("Actions[10].Verb = %q, want %q", tx.Actions[10].Verb, "start_T3")
	}
	if tx.Actions[10].Kind != Processing {
		t.Errorf("Actions[10].Kind = %v, want Processing", tx.Actions[10].Kind)
	}
	if tx.Actions[11].Verb != "RC := 0" {
		t.Errorf("Actions[11].Verb = %q, want %q", tx.Actions[11].Verb, "RC := 0")
	}
	if tx.Actions[11].Kind != Processing {
		t.Errorf("Actions[11].Kind = %v, want Processing", tx.Actions[11].Kind)
	}
}

func TestDataLinkDisconnected_t15_sabm_received_unable(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t15_sabm_received_unable" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t15_sabm_received_unable not found")
	}
	if tx.On != "SABM_received" {
		t.Errorf("On = %q, want SABM_received", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if tx.Guard != "not able_to_establish" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not able_to_establish")
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "DM" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "DM")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
}

func TestDataLinkDisconnected_t16_sabme_received_able(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t16_sabme_received_able" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t16_sabme_received_able not found")
	}
	if tx.On != "SABME_received" {
		t.Errorf("On = %q, want SABME_received", tx.On)
	}
	if tx.Next != "Connected" {
		t.Errorf("Next = %q, want Connected", tx.Next)
	}
	if tx.Guard != "able_to_establish" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "able_to_establish")
	}
	if got := len(tx.Actions); got != 12 {
		t.Fatalf("len(Actions) = %d, want 12", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "set_version_2_2" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "set_version_2_2")
	}
	if tx.Actions[1].Kind != Processing {
		t.Errorf("Actions[1].Kind = %v, want Processing", tx.Actions[1].Kind)
	}
	if tx.Actions[2].Verb != "UA" {
		t.Errorf("Actions[2].Verb = %q, want %q", tx.Actions[2].Verb, "UA")
	}
	if tx.Actions[2].Kind != SignalLower {
		t.Errorf("Actions[2].Kind = %v, want SignalLower", tx.Actions[2].Kind)
	}
	if tx.Actions[3].Verb != "Clear_Exception_Conditions" {
		t.Errorf("Actions[3].Verb = %q, want %q", tx.Actions[3].Verb, "Clear_Exception_Conditions")
	}
	if tx.Actions[3].Kind != Subroutine {
		t.Errorf("Actions[3].Kind = %v, want Subroutine", tx.Actions[3].Kind)
	}
	if tx.Actions[4].Verb != "V(s) := 0" {
		t.Errorf("Actions[4].Verb = %q, want %q", tx.Actions[4].Verb, "V(s) := 0")
	}
	if tx.Actions[4].Kind != Processing {
		t.Errorf("Actions[4].Kind = %v, want Processing", tx.Actions[4].Kind)
	}
	if tx.Actions[5].Verb != "V(a) := 0" {
		t.Errorf("Actions[5].Verb = %q, want %q", tx.Actions[5].Verb, "V(a) := 0")
	}
	if tx.Actions[5].Kind != Processing {
		t.Errorf("Actions[5].Kind = %v, want Processing", tx.Actions[5].Kind)
	}
	if tx.Actions[6].Verb != "V(r) := 0" {
		t.Errorf("Actions[6].Verb = %q, want %q", tx.Actions[6].Verb, "V(r) := 0")
	}
	if tx.Actions[6].Kind != Processing {
		t.Errorf("Actions[6].Kind = %v, want Processing", tx.Actions[6].Kind)
	}
	if tx.Actions[7].Verb != "DL_CONNECT_indication" {
		t.Errorf("Actions[7].Verb = %q, want %q", tx.Actions[7].Verb, "DL_CONNECT_indication")
	}
	if tx.Actions[7].Kind != SignalUpper {
		t.Errorf("Actions[7].Kind = %v, want SignalUpper", tx.Actions[7].Kind)
	}
	if tx.Actions[8].Verb != "SRT := Initial Default" {
		t.Errorf("Actions[8].Verb = %q, want %q", tx.Actions[8].Verb, "SRT := Initial Default")
	}
	if tx.Actions[8].Kind != Processing {
		t.Errorf("Actions[8].Kind = %v, want Processing", tx.Actions[8].Kind)
	}
	if tx.Actions[9].Verb != "T1V := 2 * SRT" {
		t.Errorf("Actions[9].Verb = %q, want %q", tx.Actions[9].Verb, "T1V := 2 * SRT")
	}
	if tx.Actions[9].Kind != Processing {
		t.Errorf("Actions[9].Kind = %v, want Processing", tx.Actions[9].Kind)
	}
	if tx.Actions[10].Verb != "start_T3" {
		t.Errorf("Actions[10].Verb = %q, want %q", tx.Actions[10].Verb, "start_T3")
	}
	if tx.Actions[10].Kind != Processing {
		t.Errorf("Actions[10].Kind = %v, want Processing", tx.Actions[10].Kind)
	}
	if tx.Actions[11].Verb != "RC := 0" {
		t.Errorf("Actions[11].Verb = %q, want %q", tx.Actions[11].Verb, "RC := 0")
	}
	if tx.Actions[11].Kind != Processing {
		t.Errorf("Actions[11].Kind = %v, want Processing", tx.Actions[11].Kind)
	}
}

func TestDataLinkDisconnected_t17_sabme_received_unable(t *testing.T) {
	var tx *TransitionSpec
	for i := range DataLinkDisconnected.Transitions {
		if DataLinkDisconnected.Transitions[i].ID == "t17_sabme_received_unable" {
			tx = &DataLinkDisconnected.Transitions[i]
			break
		}
	}
	if tx == nil {
		t.Fatalf("transition t17_sabme_received_unable not found")
	}
	if tx.On != "SABME_received" {
		t.Errorf("On = %q, want SABME_received", tx.On)
	}
	if tx.Next != "Disconnected" {
		t.Errorf("Next = %q, want Disconnected", tx.Next)
	}
	if tx.Guard != "not able_to_establish" {
		t.Errorf("Guard = %q, want %q", tx.Guard, "not able_to_establish")
	}
	if got := len(tx.Actions); got != 2 {
		t.Fatalf("len(Actions) = %d, want 2", got)
	}
	if tx.Actions[0].Verb != "F := P" {
		t.Errorf("Actions[0].Verb = %q, want %q", tx.Actions[0].Verb, "F := P")
	}
	if tx.Actions[0].Kind != Processing {
		t.Errorf("Actions[0].Kind = %v, want Processing", tx.Actions[0].Kind)
	}
	if tx.Actions[1].Verb != "DM" {
		t.Errorf("Actions[1].Verb = %q, want %q", tx.Actions[1].Verb, "DM")
	}
	if tx.Actions[1].Kind != SignalLower {
		t.Errorf("Actions[1].Kind = %v, want SignalLower", tx.Actions[1].Kind)
	}
}
