// <auto-generated>
//   This file was produced by tools/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.
//   Do not edit by hand. Run `dotnet run --project tools/Packet.Sdl.CodeGen` to regenerate.
// </auto-generated>

using System.Collections.Generic;

namespace Packet.Ax25.Sdl;

/// <summary>SDL transitions for the <c>Connected</c> state of the <c>data_link</c> machine.</summary>
/// <remarks>Source: ax.25.2.2.4_Oct_25 figc4.4a.</remarks>
public static class DataLink_Connected
{
    public const string Machine = "data_link";
    public const string State = "Connected";

    public static SdlSource Source { get; } = new("ax.25.2.2.4_Oct_25", "figc4.4a", "https://raw.githubusercontent.com/packethacking/ax25spec/main/doc/media/figc4.4a.png");

    public static IReadOnlyList<TransitionSpec> Transitions { get; } = new TransitionSpec[]
    {
        new TransitionSpec(
            Id: "t01_dl_flow_off_when_own_receiver_busy",
            From: "Connected",
            On: "DL_FLOW_OFF_request",
            Guard: "own_receiver_busy",
            Actions: new string[] { "set_own_receiver_busy", "RNR response", "clear_acknowledge_pending" },
            Next: "Connected",
            Notes: "figc4.4a col 5, Yes branch of 'Own Receiver Busy?'. Transcribed by M0LTE 2026-05-11; semantics confirmed by upstream collaborator + figure semantics consistent with direwolf ax25_link.c."),
        new TransitionSpec(
            Id: "t02_dl_flow_off_when_own_receiver_not_busy",
            From: "Connected",
            On: "DL_FLOW_OFF_request",
            Guard: "not own_receiver_busy",
            Actions: new string[] {  },
            Next: "Connected",
            Notes: "figc4.4a col 5, No branch of 'Own Receiver Busy?'. Transcribed by M0LTE 2026-05-11. Per direwolf this path is unreachable in practice."),
        new TransitionSpec(
            Id: "t03_dl_flow_on_when_own_receiver_not_busy",
            From: "Connected",
            On: "DL_FLOW_ON_request",
            Guard: "not own_receiver_busy",
            Actions: new string[] {  },
            Next: "Connected",
            Notes: "figc4.4a col 6, No branch of 'Own Receiver Busy?'. Transcribed by M0LTE 2026-05-11."),
        new TransitionSpec(
            Id: "t04_dl_flow_on_when_busy_and_T1_not_running",
            From: "Connected",
            On: "DL_FLOW_ON_request",
            Guard: "own_receiver_busy and not T1_running",
            Actions: new string[] { "clear_own_receiver_busy", "RR command", "clear_acknowledge_pending", "stop_T3", "start_T1" },
            Next: "Connected",
            Notes: "figc4.4a col 6, Yes branch with inner 'T1 Running?' = No. Transcribed by M0LTE 2026-05-11. RR command poll + T3→T1 swap matches §6.4.11."),
        new TransitionSpec(
            Id: "t05_dl_flow_on_when_busy_and_T1_running",
            From: "Connected",
            On: "DL_FLOW_ON_request",
            Guard: "own_receiver_busy and T1_running",
            Actions: new string[] { "clear_own_receiver_busy", "RR command", "clear_acknowledge_pending" },
            Next: "Connected",
            Notes: "figc4.4a col 6, Yes branch with inner 'T1 Running?' = Yes. Transcribed by M0LTE 2026-05-11. T1 already running so no timer swap needed."),
    };
}
