// <auto-generated>
//   This file was produced by tools/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.
//   Do not edit by hand. Run `dotnet run --project tools/Packet.Sdl.CodeGen` to regenerate.
// </auto-generated>

using System.Collections.Generic;

namespace Packet.Ax25.Sdl;

/// <summary>SDL transitions for the <c>Disconnected</c> state of the <c>data_link</c> machine.</summary>
/// <remarks>Source: ax.25.2.2.4_Oct_25 figc4.1.</remarks>
public static class DataLink_Disconnected
{
    public const string Machine = "data_link";
    public const string State = "Disconnected";

    public static SdlSource Source { get; } = new("ax.25.2.2.4_Oct_25", "figc4.1", "https://raw.githubusercontent.com/packethacking/ax25spec/main/doc/media/figc4.1.png");

    public static IReadOnlyList<TransitionSpec> Transitions { get; } = new TransitionSpec[]
    {
        new TransitionSpec(
            Id: "t01_dl_disconnect_request",
            From: "Disconnected",
            On: "DL_DISCONNECT_request",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("DL_DISCONNECT_confirm", ActionKind.SignalUpper) },
            Next: "Disconnected",
            Notes: null),
        new TransitionSpec(
            Id: "t02_dl_unit_data_request",
            From: "Disconnected",
            On: "DL_UNIT_DATA_request",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("UI_command", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: null),
        new TransitionSpec(
            Id: "t03_dl_connect_request",
            From: "Disconnected",
            On: "DL_CONNECT_request",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("SRT := Initial Default", ActionKind.Processing), new ActionStep("T1V := 2 * SRT", ActionKind.Processing), new ActionStep("Establish_Data_Link", ActionKind.Subroutine), new ActionStep("set_layer_3_initiated", ActionKind.Processing) },
            Next: "AwaitingConnection",
            Notes: null),
        new TransitionSpec(
            Id: "t04_all_other_primitives_from_lower_layer",
            From: "Disconnected",
            On: "all_other_primitives__from_lower_layer",
            Guard: null,
            Actions: new ActionStep[] {  },
            Next: "Disconnected",
            Notes: "Catch-all column with no actions: receive any unhandled primitive\ndrawn with the \"Signal reception from Lower Layer\" shape, stay in\nDisconnected, do nothing.\n"),
        new TransitionSpec(
            Id: "t05_all_other_commands",
            From: "Disconnected",
            On: "all_other_commands",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("DM", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: "Catch-all for received command frames not handled by SABM/SABME/\nDISC/UI explicitly: respond DM.\n"),
        new TransitionSpec(
            Id: "t06_all_other_primitives_from_upper_layer",
            From: "Disconnected",
            On: "all_other_primitives__from_upper_layer",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("discard_primitive", ActionKind.Processing) },
            Next: "Disconnected",
            Notes: null),
        new TransitionSpec(
            Id: "t07_control_field_error",
            From: "Disconnected",
            On: "control_field_error",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("DL_ERROR_indication_L", ActionKind.SignalUpper) },
            Next: "Disconnected",
            Notes: null),
        new TransitionSpec(
            Id: "t08_info_not_permitted_in_frame",
            From: "Disconnected",
            On: "info_not_permitted_in_frame",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("DL_ERROR_indication_M", ActionKind.SignalUpper) },
            Next: "Disconnected",
            Notes: null),
        new TransitionSpec(
            Id: "t09_u_or_s_frame_length_error",
            From: "Disconnected",
            On: "u_or_s_frame_length_error",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("DL_ERROR_indication_N", ActionKind.SignalUpper) },
            Next: "Disconnected",
            Notes: null),
        new TransitionSpec(
            Id: "t10_ua_received",
            From: "Disconnected",
            On: "UA_received",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("DL_ERROR_indication_C_D", ActionKind.SignalUpper) },
            Next: "Disconnected",
            Notes: null),
        new TransitionSpec(
            Id: "t11_ui_received_p_eq_1",
            From: "Disconnected",
            On: "UI_received",
            Guard: "P_eq_1",
            Actions: new ActionStep[] { new ActionStep("UI_Check", ActionKind.Subroutine), new ActionStep("F := 1", ActionKind.Processing), new ActionStep("DM", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: null),
        new TransitionSpec(
            Id: "t12_ui_received_p_eq_0",
            From: "Disconnected",
            On: "UI_received",
            Guard: "not P_eq_1",
            Actions: new ActionStep[] { new ActionStep("UI_Check", ActionKind.Subroutine) },
            Next: "Disconnected",
            Notes: null),
        new TransitionSpec(
            Id: "t13_disc_received",
            From: "Disconnected",
            On: "DISC_received",
            Guard: null,
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("DM", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: null),
        new TransitionSpec(
            Id: "t14_sabm_received_able",
            From: "Disconnected",
            On: "SABM_received",
            Guard: "able_to_establish",
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("set_version_2_0", ActionKind.Processing), new ActionStep("UA", ActionKind.SignalLower), new ActionStep("Clear_Exception_Conditions", ActionKind.Subroutine), new ActionStep("V(s) := 0", ActionKind.Processing), new ActionStep("V(a) := 0", ActionKind.Processing), new ActionStep("V(r) := 0", ActionKind.Processing), new ActionStep("DL_CONNECT_indication", ActionKind.SignalUpper), new ActionStep("SRT := Initial Default", ActionKind.Processing), new ActionStep("T1V := 2 * SRT", ActionKind.Processing), new ActionStep("start_T3", ActionKind.Processing), new ActionStep("RC := 0", ActionKind.Processing) },
            Next: "Connected",
            Notes: null),
        new TransitionSpec(
            Id: "t15_sabm_received_unable",
            From: "Disconnected",
            On: "SABM_received",
            Guard: "not able_to_establish",
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("DM", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: null),
        new TransitionSpec(
            Id: "t16_sabme_received_able",
            From: "Disconnected",
            On: "SABME_received",
            Guard: "able_to_establish",
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("set_version_2_2", ActionKind.Processing), new ActionStep("UA", ActionKind.SignalLower), new ActionStep("Clear_Exception_Conditions", ActionKind.Subroutine), new ActionStep("V(s) := 0", ActionKind.Processing), new ActionStep("V(a) := 0", ActionKind.Processing), new ActionStep("V(r) := 0", ActionKind.Processing), new ActionStep("DL_CONNECT_indication", ActionKind.SignalUpper), new ActionStep("SRT := Initial Default", ActionKind.Processing), new ActionStep("T1V := 2 * SRT", ActionKind.Processing), new ActionStep("start_T3", ActionKind.Processing), new ActionStep("RC := 0", ActionKind.Processing) },
            Next: "Connected",
            Notes: null),
        new TransitionSpec(
            Id: "t17_sabme_received_unable",
            From: "Disconnected",
            On: "SABME_received",
            Guard: "not able_to_establish",
            Actions: new ActionStep[] { new ActionStep("F := P", ActionKind.Processing), new ActionStep("DM", ActionKind.SignalLower) },
            Next: "Disconnected",
            Notes: null),
    };
}
