using System.Globalization;
using System.Text;
using YamlDotNet.Serialization;
using YamlDotNet.Serialization.NamingConventions;

namespace Packet.Sdl.CodeGen;

internal static class Program
{
    private const string GeneratedHeader =
        "// <auto-generated>\n" +
        "//   This file was produced by tools/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.\n" +
        "//   Do not edit by hand. Run `dotnet run --project tools/Packet.Sdl.CodeGen` to regenerate.\n" +
        "// </auto-generated>\n";

    public static int Main(string[] args)
    {
        string inDir = "spec-sdl";
        string outDir = "src/Packet.Ax25.Sdl";
        string testsDir = "tests/Packet.Ax25.Conformance.Tests";
        string? mermaidDir = null;  // null = "alongside the source YAML"

        for (int i = 0; i < args.Length - 1; i++)
        {
            switch (args[i])
            {
                case "--in":      inDir      = args[++i]; break;
                case "--out":     outDir     = args[++i]; break;
                case "--tests":   testsDir   = args[++i]; break;
                case "--mermaid": mermaidDir = args[++i]; break;
            }
        }

        try
        {
            return Run(inDir, outDir, testsDir, mermaidDir);
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"::error::{ex.Message}");
            return 1;
        }
    }

    private static int Run(string inDir, string outDir, string testsDir, string? mermaidDir)
    {
        if (!Directory.Exists(inDir))
        {
            Console.Error.WriteLine($"::warning::SDL input directory '{inDir}' does not exist; nothing to do.");
            return 0;
        }

        Directory.CreateDirectory(outDir);
        Directory.CreateDirectory(testsDir);

        var events = LoadEventCatalog(Path.Combine(inDir, "events.yaml"));

        var pages = Directory.EnumerateFiles(inDir, "*.sdl.yaml", SearchOption.AllDirectories)
            .OrderBy(p => p, StringComparer.Ordinal)
            .Select(LoadPage)
            .ToList();

        var errors = new List<string>();
        foreach (var page in pages)
        {
            ValidatePage(page, events, errors);
        }

        if (errors.Count > 0)
        {
            foreach (var e in errors) Console.Error.WriteLine($"::error::{e}");
            return 1;
        }

        var writtenCode    = new HashSet<string>(StringComparer.Ordinal);
        var writtenTests   = new HashSet<string>(StringComparer.Ordinal);
        var writtenMermaid = new HashSet<string>(StringComparer.Ordinal);

        foreach (var page in pages)
        {
            var fileBase = $"{Pascal(page.Machine)}_{page.State}";

            var codePath  = Path.Combine(outDir,   fileBase + ".g.cs");
            var testsPath = Path.Combine(testsDir, fileBase + ".g.Tests.cs");

            WriteIfChanged(codePath,  EmitCode(page));
            WriteIfChanged(testsPath, EmitTests(page));

            writtenCode.Add(Path.GetFullPath(codePath));
            writtenTests.Add(Path.GetFullPath(testsPath));

            // Mermaid output goes either alongside the source YAML (default,
            // so PR diffs show YAML + .g.mmd side-by-side) or in an explicit
            // directory when --mermaid is set.
            var mermaidPath = mermaidDir is null
                ? Path.Combine(Path.GetDirectoryName(page.SourcePath)!, $"{Path.GetFileNameWithoutExtension(page.SourcePath).Replace(".sdl", string.Empty, StringComparison.Ordinal)}.g.mmd")
                : Path.Combine(mermaidDir, fileBase + ".g.mmd");
            WriteIfChanged(mermaidPath, EmitMermaid(page));
            writtenMermaid.Add(Path.GetFullPath(mermaidPath));

            Console.WriteLine($"  ok  {page.SourcePath}  →  {fileBase}.{{g.cs,g.Tests.cs,g.mmd}}");
        }

        // Tidy stale generated files (someone deleted a *.sdl.yaml).
        CleanStaleFiles(outDir,   "*.g.cs",       writtenCode);
        CleanStaleFiles(testsDir, "*.g.Tests.cs", writtenTests);
        if (mermaidDir is not null)
        {
            CleanStaleFiles(mermaidDir, "*.g.mmd", writtenMermaid);
        }
        else
        {
            // When .mmd files live next to their .sdl.yaml, sweep each
            // subdirectory of inDir.
            foreach (var dir in Directory.EnumerateDirectories(inDir, "*", SearchOption.AllDirectories))
            {
                CleanStaleFiles(dir, "*.g.mmd", writtenMermaid);
            }
        }

        Console.WriteLine($"generated {pages.Count} state machine page(s)");
        return 0;
    }

    private static HashSet<string> LoadEventCatalog(string path)
    {
        if (!File.Exists(path)) return new HashSet<string>(StringComparer.Ordinal);

        var deserializer = new DeserializerBuilder()
            .WithNamingConvention(LowerCaseNamingConvention.Instance)
            .IgnoreUnmatchedProperties()
            .Build();

        var catalog = deserializer.Deserialize<Dictionary<string, List<string>>>(File.ReadAllText(path));
        var set = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (_, items) in catalog)
        {
            foreach (var item in items)
            {
                set.Add(item);
            }
        }
        return set;
    }

    private static SdlPage LoadPage(string path)
    {
        var deserializer = new DeserializerBuilder()
            .WithNamingConvention(LowerCaseNamingConvention.Instance)
            .IgnoreUnmatchedProperties()
            .Build();

        var page = deserializer.Deserialize<SdlPage>(File.ReadAllText(path))
                   ?? throw new InvalidDataException($"could not parse {path}");
        page.SourcePath = path;
        page.Transitions ??= new();
        return page;
    }

    private static void ValidatePage(SdlPage page, HashSet<string> events, List<string> errors)
    {
        var loc = page.SourcePath;
        if (string.IsNullOrWhiteSpace(page.Machine))   errors.Add($"{loc}: missing `machine`");
        if (string.IsNullOrWhiteSpace(page.State))     errors.Add($"{loc}: missing `state`");
        if (page.Source is null)                       errors.Add($"{loc}: missing `source`");
        if (page.Transitions.Count == 0)               errors.Add($"{loc}: at least one transition required");

        var ids = new HashSet<string>(StringComparer.Ordinal);
        foreach (var t in page.Transitions)
        {
            if (string.IsNullOrWhiteSpace(t.Id))   errors.Add($"{loc}: transition missing `id`");
            else if (!ids.Add(t.Id))               errors.Add($"{loc}: duplicate transition id `{t.Id}`");

            if (string.IsNullOrWhiteSpace(t.On))   errors.Add($"{loc}: transition `{t.Id}` missing `on`");
            else if (events.Count > 0 && !events.Contains(t.On))
                errors.Add($"{loc}: transition `{t.Id}` references unknown event `{t.On}`. Add it to /spec-sdl/events.yaml.");

            if (string.IsNullOrWhiteSpace(t.Next)) errors.Add($"{loc}: transition `{t.Id}` missing `next`");
        }
    }

    private static string EmitCode(SdlPage page)
    {
        var sb = new StringBuilder();
        sb.Append(GeneratedHeader);
        sb.Append('\n');
        sb.Append("using System.Collections.Generic;\n\n");
        sb.Append("namespace Packet.Ax25.Sdl;\n\n");
        sb.AppendFormat(CultureInfo.InvariantCulture,
            "/// <summary>SDL transitions for the <c>{0}</c> state of the <c>{1}</c> machine.</summary>\n",
            page.State, page.Machine);
        sb.AppendFormat(CultureInfo.InvariantCulture,
            "/// <remarks>Source: {0} {1}.</remarks>\n",
            page.Source!.Spec, page.Source.Figure);
        sb.AppendFormat(CultureInfo.InvariantCulture,
            "public static class {0}_{1}\n{{\n", Pascal(page.Machine), page.State);
        sb.AppendFormat(CultureInfo.InvariantCulture,
            "    public const string Machine = \"{0}\";\n", page.Machine);
        sb.AppendFormat(CultureInfo.InvariantCulture,
            "    public const string State = \"{0}\";\n\n", page.State);
        sb.AppendFormat(CultureInfo.InvariantCulture,
            "    public static SdlSource Source {{ get; }} = new(\"{0}\", \"{1}\", {2});\n\n",
            page.Source.Spec, page.Source.Figure,
            page.Source.Url is null ? "null" : $"\"{page.Source.Url}\"");
        sb.Append("    public static IReadOnlyList<TransitionSpec> Transitions { get; } = new TransitionSpec[]\n");
        sb.Append("    {\n");
        foreach (var t in page.Transitions)
        {
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "        new TransitionSpec(\n            Id: \"{0}\",\n            From: \"{1}\",\n            On: \"{2}\",\n            Guard: {3},\n            Actions: new string[] {{ {4} }},\n            Next: \"{5}\",\n            Notes: {6}),\n",
                t.Id, page.State, t.On,
                t.Guard is null ? "null" : EscapeString(t.Guard),
                string.Join(", ", (t.Actions ?? new()).Select(EscapeString)),
                t.Next,
                t.Notes is null ? "null" : EscapeString(t.Notes));
        }
        sb.Append("    };\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    private static string EmitTests(SdlPage page)
    {
        var sb = new StringBuilder();
        sb.Append(GeneratedHeader);
        sb.Append('\n');
        sb.Append("using System.Linq;\n");
        sb.Append("using Packet.Ax25.Sdl;\n");
        sb.Append("using Shouldly;\n");
        sb.Append("using Xunit;\n\n");
        sb.Append("namespace Packet.Ax25.Conformance.Tests;\n\n");
        sb.AppendFormat(CultureInfo.InvariantCulture,
            "public class {0}_{1}_GeneratedTests\n{{\n", Pascal(page.Machine), page.State);

        sb.AppendFormat(CultureInfo.InvariantCulture,
            "    [Fact] public void SourceFigure() => {0}_{1}.Source.Figure.ShouldBe(\"{2}\");\n\n",
            Pascal(page.Machine), page.State, page.Source!.Figure);

        sb.AppendFormat(CultureInfo.InvariantCulture,
            "    [Fact] public void TransitionsArePresent() => {0}_{1}.Transitions.Count.ShouldBe({2});\n\n",
            Pascal(page.Machine), page.State, page.Transitions.Count);

        foreach (var t in page.Transitions)
        {
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "    [Fact] public void {0}()\n    {{\n", t.Id);
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "        var t = {0}_{1}.Transitions.Single(x => x.Id == \"{2}\");\n",
                Pascal(page.Machine), page.State, t.Id);
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "        t.On.ShouldBe(\"{0}\");\n", t.On);
            sb.AppendFormat(CultureInfo.InvariantCulture,
                "        t.Next.ShouldBe(\"{0}\");\n", t.Next);
            if (t.Guard is not null)
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "        t.Guard.ShouldBe({0});\n", EscapeString(t.Guard));
            foreach (var a in t.Actions ?? new())
                sb.AppendFormat(CultureInfo.InvariantCulture,
                    "        t.Actions.ShouldContain({0});\n", EscapeString(a));
            sb.Append("    }\n\n");
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    private static string EmitMermaid(SdlPage page)
    {
        var sb = new StringBuilder();
        sb.Append("%% This file was produced by tools/Packet.Sdl.CodeGen from ");
        sb.Append(page.SourcePath).Append('\n');
        sb.Append("%% Do not edit by hand. Run `dotnet run --project tools/Packet.Sdl.CodeGen` to regenerate.\n");
        sb.Append("%%\n");
        sb.AppendFormat(CultureInfo.InvariantCulture,
            "%% Source: {0}, figure {1}\n", page.Source!.Spec, page.Source.Figure);
        if (page.Source.Url is { Length: > 0 })
        {
            sb.AppendFormat(CultureInfo.InvariantCulture, "%% URL: {0}\n", page.Source.Url);
        }
        sb.AppendFormat(CultureInfo.InvariantCulture, "%% Coverage: {0}\n", page.Coverage);
        sb.Append("%%\n");
        sb.Append("%% Important: this rendering is approximate and intentionally\n");
        sb.Append("%% looks nothing like the original SDL figure. It is a machine-\n");
        sb.Append("%% generated view of the transitions in the .sdl.yaml — useful\n");
        sb.Append("%% for spotting transcription bugs (missing transitions, wrong\n");
        sb.Append("%% destination state) but NOT a substitute for reading the spec\n");
        sb.Append("%% figure itself. See docs/sdl-primer.md.\n\n");

        sb.Append("stateDiagram-v2\n");
        sb.Append("    direction LR\n\n");

        var seenStates = new HashSet<string>(StringComparer.Ordinal) { page.State };
        foreach (var t in page.Transitions)
        {
            seenStates.Add(t.Next);
        }

        // Highlight the focal state visually.
        sb.AppendFormat(CultureInfo.InvariantCulture, "    classDef focal fill:#fff5b1,stroke:#b08800;\n");
        sb.AppendFormat(CultureInfo.InvariantCulture, "    class {0} focal\n\n", page.State);

        foreach (var t in page.Transitions)
        {
            string label = BuildMermaidEdgeLabel(t);
            sb.AppendFormat(CultureInfo.InvariantCulture, "    {0} --> {1}: {2}\n", page.State, t.Next, label);
        }

        return sb.ToString();
    }

    private static string BuildMermaidEdgeLabel(SdlTransition t)
    {
        var parts = new List<string> { t.Id };
        parts.Add($"on: {EscapeMermaid(t.On)}");
        if (!string.IsNullOrEmpty(t.Guard))
        {
            parts.Add($"[{EscapeMermaid(t.Guard)}]");
        }
        foreach (var a in t.Actions ?? new())
        {
            parts.Add($"/ {EscapeMermaid(a)}");
        }
        return string.Join("<br/>", parts);
    }

    private static string EscapeMermaid(string s)
    {
        // Mermaid label-special chars: " breaks parsing, newlines aren't
        // allowed inline (we use <br/> instead), and we strip CRs for
        // consistency.
        return s
            .Replace("\"", "&quot;", StringComparison.Ordinal)
            .Replace("\n", " ",      StringComparison.Ordinal)
            .Replace("\r", string.Empty, StringComparison.Ordinal);
    }

    private static void WriteIfChanged(string path, string contents)
    {
        if (File.Exists(path) && File.ReadAllText(path) == contents) return;
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, contents);
    }

    private static void CleanStaleFiles(string dir, string pattern, HashSet<string> keep)
    {
        if (!Directory.Exists(dir)) return;
        foreach (var f in Directory.EnumerateFiles(dir, pattern))
        {
            if (!keep.Contains(Path.GetFullPath(f)))
            {
                File.Delete(f);
                Console.WriteLine($"  removed stale {f}");
            }
        }
    }

    private static string Pascal(string snake)
    {
        var parts = snake.Split('_');
        return string.Concat(parts.Select(p => char.ToUpperInvariant(p[0]) + p[1..]));
    }

    private static string EscapeString(string s)
    {
        var escaped = s
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t");
        return "\"" + escaped + "\"";
    }
}

internal sealed class SdlPage
{
    public string Machine { get; set; } = "";
    public string State { get; set; } = "";
    public string Coverage { get; set; } = "complete";
    public SdlSourceYaml? Source { get; set; }
    public List<string>? Variables { get; set; }
    public List<SdlTransition> Transitions { get; set; } = new();
    [YamlIgnore] public string SourcePath { get; set; } = "";
}

internal sealed class SdlSourceYaml
{
    public string Spec { get; set; } = "";
    public string Figure { get; set; } = "";
    public string? Url { get; set; }
}

internal sealed class SdlTransition
{
    public string Id { get; set; } = "";
    public string On { get; set; } = "";
    public string? Guard { get; set; }
    public List<string>? Actions { get; set; }
    public string Next { get; set; } = "";
    public string? Notes { get; set; }
}
